apiVersion: v1
kind: Namespace
metadata:
  labels:
    product: aes
  name: ambassador
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-stack-agent
  namespace: ambassador
  labels:
    app.kubernetes.io/name: edge-stack-agent
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/part-of: edge-stack
    app.kubernetes.io/managed-by: getambassador.io
    product: aes
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: edge-stack
  namespace: ambassador
  labels:
    app.kubernetes.io/name: edge-stack
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/part-of: edge-stack
    app.kubernetes.io/managed-by: getambassador.io
    product: aes
---
apiVersion: v1
kind: Secret
metadata:
  name: edge-stack
  namespace: ambassador
type: Opaque
data:
  license-key: <base64-encoded-license-key>
---
apiVersion: v1
kind: Secret
metadata:
  name: fallback-self-signed-cert
  namespace: ambassador
type: kubernetes.io/tls
data:
  tls.crt: <base64-encoded-tls-crt>
  tls.key: <base64-encoded-tls-key>
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: edge-stack-agent
  labels:
    app.kubernetes.io/name: edge-stack-agent
    app.kubernetes.io/instance: edge-stack
    app.kubernetes.io/part-of: edge-stack
    app
