apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd # replace with your namespace if different
data:
  url: https://argocd.minikube.local
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $dex-github-secret:clientID
        clientSecret: $dex-github-secret:clientSecret
        orgs:
        - name: DEVOPS-NEW-YORK-PHIL-GEORGIE
